# Generated by Django 6.1.1 on 2026-09-23 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Непустая строка до 120 символов', max_length=120, verbose_name='Имя автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Непустая строка до 120 символов', max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Непустая строка до 5000 символов', max_length=5000, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена в рублях от 0 до 999999999.99', max_digits=11, verbose_name='Цена')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'В архиве')], default='draft', help_text='draft/published/archived', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(help_text='Связь с автором объявления', on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
